# Generated by Django 3.1.7 on 2021-04-23 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210413_0251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-expertivity',)},
        ),
        migrations.AddField(
            model_name='review',
            name='expertivity',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='book_image',
            field=models.ImageField(blank=True, upload_to='posts/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
