# Generated by Django 3.1.2 on 2021-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'follow'), ('send', 'unfollow')], max_length=8),
        ),
    ]
